[tool.ruff]
exclude = [
    "__init__.py",
    "doc/conf.py",
    "doc/_build/html/conf.py",
    "tests/data/*",
    "tests/.tests/*",
]
ignore = [
    "N802",
    "N803",
    "N806",
    "N812",
    "N815",
    "N816",
    "N999",
    "D107",
    "D105",
    "D102",
    "D104",
    "D100",
    "D200",
    "D205",
    "D400",
    "E402", # Module level import not at top of file (against Rubin style)
]
line-length = 110
select = [
    "E",
    "F",
    "N",
    "W",
]
